example_app/urls.py
from django.urls import path

from .views import settings_home
from looper.views import checkout_stripe, settings

urlpatterns = [
    # The settings/ path prefix is shared between this module and looper.urls.
    path('settings/', settings_home, name='settings_home'),
    path('settings/receipts/', settings.settings_receipts, name='settings_receipts'),
    path('settings/receipts/<int:order_id>', settings.ReceiptView.as_view(),
         name='settings_receipt'),
    path('settings/receipts/example-app-<int:order_id>.pdf',
         settings.ReceiptPDFView.as_view(),
         name='settings_receipt_pdf'),
    path(
        'settings/billing/payment-methods/change/<int:subscription_id>',
        settings.PaymentMethodChangeView.as_view(
            success_url='payment_method_change_done',
            cancel_url='settings_home',
        ),
        name='payment_method_change',
    ),
    path(
        'settings/billing/payment-methods/change-done/<int:subscription_id>/<stripe_session_id>',
        # TODO? settings_home redirects to settings_membership_edit if there is just one membership
        # so this is good for 99%
        # as an improvement we could make success_url parameter a callable that does a proper
        # pk lookup and explicitly redirects to settings_membership_edit
        settings.PaymentMethodChangeDoneView.as_view(success_url='settings_home'),
        name='payment_method_change_done',
    ),
    path(
        'stripe-success-create-subscription/<stripe_session_id>',
        checkout_stripe.StripeSuccessCreateSubscriptionView.as_view(),
        name='stripe_success_create_subscription',
    ),
]

looper/urls.py
from django.urls import path

from .views import checkout, checkout_stripe, settings, preferred_currency

app_name = 'looper'
urlpatterns = [
    path(
        'checkout/<int:plan_id>',
        checkout.ChooseDefaultPlanVariationView.as_view(pattern_name='looper:checkout'),
        name='checkout_new',
    ),
    path(
        'checkout/<int:plan_id>/choose/<int:current_plan_variation_id>',
        checkout.ChoosePlanVariationView.as_view(),
        name='checkout_choose_plan_variation',
    ),
    path(
        'checkout/<int:plan_id>/variation/<int:plan_variation_id>',
        checkout_stripe.CheckoutStripeView.as_view(),
        name='checkout',
    ),
    path(
        'stripe_success/<int:pk>/<stripe_session_id>',
        checkout_stripe.StripeSuccessView.as_view(),
        name='stripe_success',
    ),
    path(
        'checkout/pay/<int:order_id>',
        checkout_stripe.CheckoutExistingOrderView.as_view(),
        name='checkout_existing_order',
    ),
    path('checkout/done/<int:transaction_id>', checkout.DoneView.as_view(), name='checkout_done'),
    path(
        'checkout/<gateway_name>/<int:pk>',
        checkout.TransactionlessCheckoutDoneView.as_view(),
        name='transactionless_checkout_done',
    ),
    path('settings/billing/', settings.BillingAddressView.as_view(), name='settings_billing_info'),
    path(
        'settings/billing/payment-methods/',
        settings.PaymentMethodsView.as_view(),
        name='payment_methods',
    ),
    path(
        'settings/billing/payment-methods/delete/<int:pk>',
        settings.PaymentMethodDeleteView.as_view(),
        name='payment_method_delete',
    ),
    # Note: this URL is used hardcodedly in scripts/tutti/02_currency.js
    path(
        'preferred-currency',
        preferred_currency.CurrencySelectorView.as_view(),
        name='preferred_currency',
    ),
]

example_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def settings_home(request):
    return render(request, 'settings/home.html', context={})

looper/views/checkout.py
import logging

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView

from .. import middleware, models

log = logging.getLogger(__name__)


class ChooseDefaultPlanVariationView(RedirectView):
    """Chose the appropriate variation for this plan, then forward the user to checkout."""

    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        plan_id = kwargs['plan_id']
        plan = get_object_or_404(models.Plan, pk=plan_id)

        # Determine the proper plan for the user's currency.
        prefcur: str = self.request.session.get(
            middleware.PREFERRED_CURRENCY_SESSION_KEY, models.DEFAULT_CURRENCY
        )

        default_variation = plan.variation_for_currency(prefcur)
        if default_variation is None and prefcur != models.DEFAULT_CURRENCY:
            log.warning('Default variation in %s for Plan %i not found' % (prefcur, plan_id))
            # Check if the a variation is available in the default currency
            default_variation = plan.variation_for_currency(models.DEFAULT_CURRENCY)
            if default_variation is None:
                log.error('No variation for for Plan %i found' % plan_id)
                raise Http404('This Plan does not have variations at the moment.')

        url_kwargs = {'plan_id': plan_id, 'plan_variation_id': default_variation.id}
        return reverse(self.pattern_name, kwargs=url_kwargs)


class ChoosePlanVariationView(ListView):
    template_name = 'checkout/choose_plan_variation.html'

    def get(self, request, *args, **kwargs):
        self.plan = get_object_or_404(models.Plan, pk=kwargs['plan_id'])
        self.current_pv = get_object_or_404(
            self.plan.variations.active(), pk=kwargs['current_plan_variation_id']
        )
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        # Determine the current currency.
        currency: str = self.request.session.get(
            middleware.PREFERRED_CURRENCY_SESSION_KEY, models.DEFAULT_CURRENCY
        )
        # Fetch only active variations in the current currency.
        return self.plan.variations.active().filter(currency=currency)

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        return {
            **super().get_context_data(object_list=object_list, **kwargs),
            'plan': self.plan,
            'current_plan_variation': self.current_pv,
        }


class DoneView(DetailView):
    template_name = 'checkout/checkout_done.html'

    def get_object(self, queryset=None) -> models.Order:
        transaction_id: int = self.kwargs['transaction_id']
        if self.request.user.is_authenticated:
            transactions_q = models.Transaction.objects.filter(customer=self.request.user.customer)
        else:
            token = self.request.GET.get('token')
            if not token:
                raise Http404()
            transactions_q = models.Transaction.objects.filter(customer__token__token=token)
        trans: models.Transaction = get_object_or_404(transactions_q, pk=transaction_id)
        return trans.order


class TransactionlessCheckoutDoneView(DetailView):
    template_name = 'checkout/checkout_done_transactionless.html'

    def get_object(self, queryset=None) -> models.Order:
        order_id: int = self.kwargs['pk']
        if self.request.user.is_authenticated:
            order_q = models.Order.objects.filter(customer=self.request.user.customer)
        else:
            token = self.request.GET.get('token')
            if not token:
                raise Http404()
            order_q = models.Order.objects.filter(customer__token__token=token)
        return get_object_or_404(order_q, pk=order_id)

    def get_context_data(self, **kwargs) -> dict:
        gateway = get_object_or_404(models.Gateway, name=self.kwargs['gateway_name'])
        return {
            **super().get_context_data(**kwargs),
            'gateway': gateway,
        }

looper/views/checkout_stripe.py
from typing import Optional
import logging
import urllib.parse

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.generic import FormView, DetailView
import django.db.utils

from .. import forms, middleware, models, stripe_utils, utils
from looper.views.mixins import ExpectReadableIPAddressMixin

log = logging.getLogger(__name__)


class StripeSuccessView(View):
    def get(self, request, *args, **kwargs):
        order = get_object_or_404(models.Order, pk=self.kwargs['pk'])
        log.info('Processing stripe success url order pk=%s with status %s', order.pk, order.status)
        if order.status in {'paid', 'fulfilled'}:
            log.info('Order is already paid, success_url is visited twice or webhook was first')
            trans = order.latest_transaction()
        elif not order.may_transition_to('paid'):
            # should never happen here normally, TODO a proper template
            log.error(
                'Can\'t transition order pk=%s to paid: has status=%s', order.pk, order.status
            )
            return HttpResponseBadRequest()
        else:
            gateway = models.Gateway.objects.get(name='stripe')
            stripe_session_id = self.kwargs['stripe_session_id']
            stripe_session = gateway.provider.retrieve_checkout_session_expanded(stripe_session_id)
            payment_intent = stripe_session.payment_intent
            log.info('Processing payment_intent id=%s', payment_intent.id)
            if payment_intent.status != 'succeeded':
                log.error('payment_intent has status %s, won\'t process', payment_intent.status)
                return HttpResponseBadRequest()
            if int(payment_intent.metadata['order_id']) != order.pk:
                log.error(
                    'payment_intent metadata order_id=%s doesn\'t match the order.pk=%s',
                    payment_intent.metadata['order_id'], order.pk,
                )
                return HttpResponseBadRequest()

            log.info(
                'Creating a transaction based on a succeeded payment_intent pk=%s',
                payment_intent.id,
            )
            customer_ip_address = utils.get_client_ip(self.request)
            trans = stripe_utils.process_payment_intent_for_subscription_order(
                payment_intent, order, customer_ip_address
            )

        done_url = reverse('looper:checkout_done', kwargs={'transaction_id': trans.id})
        token = self.request.GET.get('token')
        if token:
            done_url += '?' + urllib.parse.urlencode({'token': token})
        return redirect(done_url)


class StripeSuccessCreateSubscriptionView(View):
    def get(self, request, *args, **kwargs):
        stripe_session_id = self.kwargs['stripe_session_id']
        gateway = models.Gateway.objects.get(name='stripe')
        stripe_session = gateway.provider.retrieve_checkout_session_expanded(stripe_session_id)
        payment_intent = stripe_session.payment_intent
        log.info('Processing payment_intent id=%s', payment_intent.id)
        if payment_intent.status != 'succeeded':
            log.error('payment_intent has status %s, won\'t process', payment_intent.status)
            return HttpResponseBadRequest()
        plan_variation_id = payment_intent.metadata.get('plan_variation_id', None)
        if not plan_variation_id:
            log.error('payment_intent.metadata is missing plan_variation_id, won\'t process')
            return HttpResponseBadRequest()

        gateway_order_id_q = models.GatewayOrderId.objects.filter(
            gateway=gateway,
            gateway_order_id=payment_intent.id,
        )
        gateway_order_id = gateway_order_id_q.first()
        if gateway_order_id:
            order = gateway_order_id.order
            if order.status in {'paid', 'fulfilled'}:
                log.info(
                    'Order pk=%s with payment_intent id=%s is already paid,'
                    ' success_url is visited twice or webhook was first',
                    order.pk, payment_intent.id,
                )
                trans = order.latest_transaction()
            else:
                log.error(
                    'Order pk=%s with payment_intent id=%s is not paid,'
                    ' won\'t process',
                    order.pk, payment_intent.id,
                )
                return HttpResponseBadRequest()
        else:
            plan_variation = get_object_or_404(
                models.PlanVariation, pk=plan_variation_id
            )
            customer_ip_address = utils.get_client_ip(self.request)
            try:
                trans = stripe_utils.process_payment_intent_for_plan_variation(
                    payment_intent,
                    plan_variation,
                    customer_ip_address,
                )
            except django.db.utils.IntegrityError as e:
                log.info(
                    'Retrying Order lookup by payment_intent id=%s,'
                    ' expected to have been written by the webhook: %s',
                    payment_intent.id, e
                )
                # if a record is missing we do want to get an exception, so using get(), not first()
                gateway_order_id = gateway_order_id_q.get()
                # intentional copy-paste of above code, for readability
                order = gateway_order_id.order
                if order.status in {'paid', 'fulfilled'}:
                    log.info(
                        'Order pk=%s with payment_intent id=%s is already paid,'
                        ' success_url is visited twice or webhook was first',
                        order.pk, payment_intent.id,
                    )
                    trans = order.latest_transaction()
                else:
                    log.error(
                        'Order pk=%s with payment_intent id=%s is not paid,'
                        ' won\'t process',
                        order.pk, payment_intent.id,
                    )
                    return HttpResponseBadRequest()

        done_url = reverse('looper:checkout_done', kwargs={'transaction_id': trans.id})
        if hasattr(trans.customer, 'token'):
            done_url += '?' + urllib.parse.urlencode({'token': trans.customer.token.token})
        return redirect(done_url)


class CheckoutExistingOrderView(LoginRequiredMixin, ExpectReadableIPAddressMixin, DetailView):
    """Perform the checkout procedure for an existing order."""

    # should be passed from the app, this url name is defined in example_app
    cancel_url = 'settings_home'

    def get_cancel_url(self):
        return reverse(self.cancel_url)

    def get_object(self, queryset=None) -> models.Order:
        order_id: int = self.kwargs['order_id']
        order_q = models.Order.objects.filter(customer=self.request.user.customer)
        return get_object_or_404(order_q, pk=order_id)

    def get(self, *args, **kwargs):
        response = self._check_customer_ip_address()
        if response:
            return response

        order = self.get_object()

        success_url = self.request.build_absolute_uri(
            reverse(
                'looper:stripe_success',
                kwargs={
                    'pk': order.id,
                    'stripe_session_id': 'CHECKOUT_SESSION_ID',
                }
            )
        )
        # we have to do it to avoid uri-encoding of curly braces,
        # otherwise stripe doesn't do the template substitution
        success_url = success_url.replace('CHECKOUT_SESSION_ID', '{CHECKOUT_SESSION_ID}', 1)
        cancel_url = self.request.build_absolute_uri(self.get_cancel_url())
        session = stripe_utils.create_stripe_checkout_session_for_order(
            order,
            success_url,
            cancel_url,
            payment_intent_metadata={'order_id': order.pk},
        )
        return redirect(session.url)


class CheckoutStripeView(ExpectReadableIPAddressMixin, FormView):
    """Perform the checkout procedure for a subscription using Stripe."""

    template_name = 'checkout/checkout_stripe.html'
    form_class = forms.CheckoutStripeForm

    customer: models.Customer
    plan: models.Plan
    plan_variation: models.PlanVariation

    def get_currency(self) -> str:
        """Returns the currency for the current page.

        Defaults to the user's preferred currency, but can be overridden
        in a subclass.
        """
        return self.request.session.get(
            middleware.PREFERRED_CURRENCY_SESSION_KEY, models.DEFAULT_CURRENCY
        )

    def dispatch(self, request, *args, **kwargs):
        # Get the prerequisites for handling any request in this view.
        self.plan = get_object_or_404(models.Plan, pk=kwargs['plan_id'])
        self.plan_variation = get_object_or_404(
            self.plan.variations.active(), pk=kwargs['plan_variation_id']
        )
        self.user = self.request.user
        if self.user.is_authenticated:
            self.customer = self.user.customer
        else:
            self.customer = models.Customer()
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict:
        ctx = {
            **super().get_context_data(**kwargs),
            'plan': self.plan,
            'plan_variation': self.plan_variation,
        }
        return ctx

    def get_form_kwargs(self) -> dict:
        return {
            **super().get_form_kwargs(),
            'instance': self.customer.billing_address,
        }

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        if self.request.method == 'GET':

example_app/templates/checkout/checkout.html
{% extends "checkout/checkout_base.html" %}
{% load looper %}
{% load pipeline %}

{% block after_header %}
<form id="payment-form" method="post" class="checkout-form pt-3"
      data-looper-payment-form="true"
      data-braintree-client-token="{{ client_token }}"
      >{% csrf_token %}
  <section class="checkout-form-fields">
    <ul class="form">{{ form.as_ul }}</ul>
    <div id="gateway-errors"></div>
  </section>
  <hr/>
  <div id="recaptcha" class="g-recaptcha"
      data-sitekey="{{ settings.GOOGLE_RECAPTCHA_SITE_KEY }}"
      data-size="invisible"></div>
  <button id="submit-button" class="btn btn-filled-success w-100"
          type="submit"
          {# will be enabled when payment gateways are initialized successfully #}
          aria-disabled="true" disabled
          ><i class="fa fa-check"></i>Subscribe</button>
</form>{% endblock %}
{% block footer_scripts %}
{% include "looper/scripts.html" %}
{% endblock %}

example_app/templates/checkout/checkout_base.html
{% extends "example_app/empty_page.html" %}
{% load looper %}

{% block content %}
<div class="checkout-container">
  <section class="checkout">
    <header>
      <div class="d-flex justify-content-between"><a class="text-muted" href="/"><i class="fa fa-angle-left pr-3"></i> Looper Example</a><a title="Change plan" href="{% url 'looper:checkout_choose_plan_variation' plan_id=plan.id current_plan_variation_id=plan_variation.id %}">Plan variations available</a></div>
      <section class="plan-info d-flex align-items-center">
        <h2 class="my-0 pt-4">{{ plan.description }}</h2>
        <h2 class="ml-auto text-secondary my-0 pt-4"><a title="Change plan" href="{% url 'looper:checkout_choose_plan_variation' plan_id=plan.id current_plan_variation_id=plan_variation.id %}"><span>{{ plan_variation|pricing }}</span></a></h2>
      </section>
    </header>
    <hr/>{% block after_header %}{% endblock %}
  </section>
</div>{% endblock %}

example_app/templates/checkout/checkout_base_empty.html
{% extends 'example_app/empty_page.html' %}

example_app/templates/checkout/checkout_done.html
{% extends 'example_app/empty_page.html' %}
{% block content %}
<div class="checkout-yay-bg py-5 checkout-container">
  <div class="container text-center py-5">
    <h1 class="thanks">Thank you {{ user.customer.full_name }}! <i class="fa fa-heart text-danger pl-3"></i></h1>
    <div class="lead pt-4">Subscription <strong>{{ order.subscription.plan }}</strong></div>
</div>
{% endblock %}

example_app/templates/checkout/checkout_done_transactionless.html
{% extends 'example_app/empty_page.html' %}
{% block content %}
<div class="checkout-yay-bg py-5 checkout-container">
  <div class="container text-center py-5">
    <h1 class="thanks">Thank you {{ user.customer.full_name }}! <i class="fa fa-heart text-danger pl-3"></i></h1>
    <div class="lead pt-4">Subscription <strong>{{ order.subscription.plan }}</strong></div>
    <p>
      Your membership will be activated as soon as we have handled your bank transfer.
      
      **Instructions follow below.**
    </p>
</div>
{% endblock %}

example_app/templates/checkout/checkout_existing_order.html
{% extends "checkout/checkout_base.html" %}
{% load looper %}
{% load pipeline %}

{% block content %}
<div class="checkout-container">
  <section class="checkout">
    <header><a class="text-muted" href="/"><i class="fa fa-angle-left pr-3"></i> Looper Example Project</a>
      <section class="plan-info d-flex align-items-center">
        <h2 class="my-0 pt-4">{{ plan.description }}</h2>
        <h2 class="ml-auto text-secondary my-0 pt-4"><span>{{ order.price.with_currency_symbol }} for {{ subscription.interval_length }} {{ subscription.interval_unit }}</span></h2>
      </section>
    </header>
    <hr/>
    <form class="checkout-form" id="payment-form" method="post"
          data-looper-payment-form="true"
          data-braintree-client-token="{{ client_token }}">{% csrf_token %}
      <section class="checkout-form-fields">
        <ul class="form">{{ form.as_ul }}</ul>
        <div id="gateway-errors"></div>
      </section>
      <hr/>
      <button class="btn-success form-submit" id="submit-button" type="submit"><span>Pay {{ order.price.with_currency_symbol }}</span></button>
    </form>
  </section>
</div>
{% include "looper/scripts.html" %}
{% endblock %}

example_app/templates/checkout/checkout_stripe.html
{% extends "checkout/checkout_base.html" %}
{% load looper %}
{% load pipeline %}

{% block after_header %}
<form id="payment-form" method="post" class="checkout-form pt-3"
      data-looper-payment-form="true"
      >{% csrf_token %}
  <section class="checkout-form-fields">
    <ul class="form">{{ form.as_ul }}</ul>
    <div id="gateway-errors"></div>
  </section>
  <hr/>
  <button id="submit-button" class="btn btn-filled-success w-100"
          type="submit"
          {# will be enabled when payment gateways are initialized successfully #}
          aria-disabled="true" disabled
          ><i class="fa fa-check"></i>Subscribe</button>
</form>{% endblock %}
{% block footer_scripts %}
{% javascript 'looper_currency' %}
{% endblock %}