looper/urls.py
from django.urls import path

from .views import checkout, checkout_stripe, settings, preferred_currency

app_name = 'looper'
urlpatterns = [
    path(
        'checkout/<int:plan_id>',
        checkout.ChooseDefaultPlanVariationView.as_view(pattern_name='looper:checkout'),
        name='checkout_new',
    ),
    path(
        'checkout/<int:plan_id>/choose/<int:current_plan_variation_id>',
        checkout.ChoosePlanVariationView.as_view(),
        name='checkout_choose_plan_variation',
    ),
    path(
        'checkout/<int:plan_id>/variation/<int:plan_variation_id>',
        checkout_stripe.CheckoutStripeView.as_view(),
        name='checkout',
    ),
    path(
        'stripe_success/<int:pk>/<stripe_session_id>',
        checkout_stripe.StripeSuccessView.as_view(),
        name='stripe_success',
    ),
    path(
        'checkout/pay/<int:order_id>',
        checkout_stripe.CheckoutExistingOrderView.as_view(),
        name='checkout_existing_order',
    ),
    path('checkout/done/<int:transaction_id>', checkout.DoneView.as_view(), name='checkout_done'),
    path(
        'checkout/<gateway_name>/<int:pk>',
        checkout.TransactionlessCheckoutDoneView.as_view(),
        name='transactionless_checkout_done',
    ),
    path('settings/billing/', settings.BillingAddressView.as_view(), name='settings_billing_info'),
    path(
        'settings/billing/payment-methods/',
        settings.PaymentMethodsView.as_view(),
        name='payment_methods',
    ),
    path(
        'settings/billing/payment-methods/delete/<int:pk>',
        settings.PaymentMethodDeleteView.as_view(),
        name='payment_method_delete',
    ),
    # Note: this URL is used hardcodedly in scripts/tutti/02_currency.js
    path(
        'preferred-currency',
        preferred_currency.CurrencySelectorView.as_view(),
        name='preferred_currency',
    ),
]

looper/views/checkout.py
import logging

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView

from .. import middleware, models

log = logging.getLogger(__name__)


class ChooseDefaultPlanVariationView(RedirectView):
    """Chose the appropriate variation for this plan, then forward the user to checkout."""

    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        plan_id = kwargs['plan_id']
        plan = get_object_or_404(models.Plan, pk=plan_id)

        # Determine the proper plan for the user's currency.
        prefcur: str = self.request.session.get(
            middleware.PREFERRED_CURRENCY_SESSION_KEY, models.DEFAULT_CURRENCY
        )

        default_variation = plan.variation_for_currency(prefcur)
        if default_variation is None and prefcur != models.DEFAULT_CURRENCY:
            log.warning('Default variation in %s for Plan %i not found' % (prefcur, plan_id))
            # Check if the a variation is available in the default currency
            default_variation = plan.variation_for_currency(models.DEFAULT_CURRENCY)
            if default_variation is None:
                log.error('No variation for for Plan %i found' % plan_id)
                raise Http404('This Plan does not have variations at the moment.')

        url_kwargs = {'plan_id': plan_id, 'plan_variation_id': default_variation.id}
        return reverse(self.pattern_name, kwargs=url_kwargs)


class ChoosePlanVariationView(ListView):
    template_name = 'checkout/choose_plan_variation.html'

    def get(self, request, *args, **kwargs):
        self.plan = get_object_or_404(models.Plan, pk=kwargs['plan_id'])
        self.current_pv = get_object_or_404(
            self.plan.variations.active(), pk=kwargs['current_plan_variation_id']
        )
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        # Determine the current currency.
        currency: str = self.request.session.get(
            middleware.PREFERRED_CURRENCY_SESSION_KEY, models.DEFAULT_CURRENCY
        )
        # Fetch only active variations in the current currency.
        return self.plan.variations.active().filter(currency=currency)

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        return {
            **super().get_context_data(object_list=object_list, **kwargs),
            'plan': self.plan,
            'current_plan_variation': self.current_pv,
        }


class DoneView(DetailView):
    template_name = 'checkout/checkout_done.html'

    def get_object(self, queryset=None) -> models.Order:
        transaction_id: int = self.kwargs['transaction_id']
        if self.request.user.is_authenticated:
            transactions_q = models.Transaction.objects.filter(customer=self.request.user.customer)
        else:
            token = self.request.GET.get('token')
            if not token:
                raise Http404()
            transactions_q = models.Transaction.objects.filter(customer__token__token=token)
        trans: models.Transaction = get_object_or_404(transactions_q, pk=transaction_id)
        return trans.order


class TransactionlessCheckoutDoneView(DetailView):
    template_name = 'checkout/checkout_done_transactionless.html'

    def get_object(self, queryset=None) -> models.Order:
        order_id: int = self.kwargs['pk']
        if self.request.user.is_authenticated:
            order_q = models.Order.objects.filter(customer=self.request.user.customer)
        else:
            token = self.request.GET.get('token')
            if not token:
                raise Http404()
            order_q = models.Order.objects.filter(customer__token__token=token)
        return get_object_or_404(order_q, pk=order_id)

    def get_context_data(self, **kwargs) -> dict:
        gateway = get_object_or_404(models.Gateway, name=self.kwargs['gateway_name'])
        return {
            **super().get_context_data(**kwargs),
            'gateway': gateway,
        }

looper/views/checkout_braintree.py
from typing import Optional, Tuple
import datetime
import logging
import urllib

import dateutil.parser
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.core.mail import mail_admins
from django.core.exceptions import ValidationError
from django.http import HttpResponse
from django.http.request import validate_host
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views.generic import FormView
import requests.adapters

from looper.forms_braintree import CheckoutForm
from .. import exceptions, middleware, models, utils

recaptcha_session = requests.Session()
recaptcha_session.mount(
    'https://',
    requests.adapters.HTTPAdapter(
        max_retries=requests.adapters.Retry(total=10, backoff_factor=0.2),
    ),
)

log = logging.getLogger(__name__)
User = get_user_model()


class AbstractPaymentView(FormView):
    """Superclass for Braintree payment screens."""

    log = log.getChild('AbstractPaymentView')

    gateway: models.Gateway
    customer: models.Customer
    session_key_prefix = 'PAYMENT_GATEWAY_CLIENT_TOKEN_'

    def dispatch(self, request, *args, **kwargs):
        if not getattr(self, 'gateway', None):
            # Only set self.gateway if it hasn't been set already. This allows
            # subclasses to override the default gateway in their dispatch()
            # method before calling super().dispatch().
            self.gateway = models.Gateway.objects.get(name__in={'braintree', 'mock'})
        self.user = self.request.user
        if self.user.is_authenticated:
            self.customer = self.user.customer
        else:
            self.customer = models.Customer()
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self) -> dict:
        return {
            'gateway': self.gateway.name,
        }

    def gateway_from_form(self, form) -> models.Gateway:
        self.gateway = form.cleaned_data['gateway']
        return self.gateway

    def get_context_data(self, **kwargs) -> dict:
        currency = self.get_currency()
        ctx = {
            **super().get_context_data(**kwargs),
            'client_token': self.get_client_token(currency),
        }
        return ctx

    def get_currency(self) -> str:
        """Returns the currency for the current page.

        Defaults to the user's preferred currency, but can be overridden
        in a subclass.
        """
        return self.request.session.get(
            middleware.PREFERRED_CURRENCY_SESSION_KEY, models.DEFAULT_CURRENCY
        )

    def client_token_session_key(self, for_currency: str) -> str:
        return f'{self.session_key_prefix}{self.gateway.pk}_{for_currency}'

    def get_client_token(self, for_currency: str) -> str:
        """Generate a Braintree client token, caching it in the session.

        This is hard-coded to Braintree instead of using the current payment
        gateway, because the user can switch between gateways in the web
        interface and thus we have to be able to show the Braintree drop-in
        UI at any moment.
        """

        sesskey = self.client_token_session_key(for_currency)
        sesskey_expiry = f'{sesskey}_expire'

        try:
            client_token = self.request.session[sesskey]
            token_expires = self.request.session[sesskey_expiry]
        except KeyError:
            pass
        else:
            expiry_timestamp = dateutil.parser.parse(token_expires)
            if expiry_timestamp > datetime.datetime.now():
                # Not yet expired, use the client token.
                return client_token

        # TODO(Sybren): handle Gateway errors.
        braintree_gw = models.Gateway.objects.get(name__in={'braintree', 'mock'})
        gateway_customer_id = self.customer.gateway_customer_id(braintree_gw)
        assert gateway_customer_id is not None, 'gateway_customer_id is missing'
        client_token = braintree_gw.provider.generate_client_token(
            for_currency, gateway_customer_id
        )

        expiry_timestamp = datetime.datetime.now() + datetime.timedelta(minutes=10)
        self.request.session[sesskey_expiry] = expiry_timestamp.isoformat()
        self.request.session[sesskey] = client_token

        return client_token

    def erase_client_token(self) -> None:
        """Erase the client token from the session."""

        to_erase = [
            key for key in self.request.session.keys() if key.startswith(self.session_key_prefix)
        ]
        for sesskey in to_erase:
            del self.request.session[sesskey]

    def _check_customer_ip_address(self, form: CheckoutForm) -> Optional[HttpResponse]:
        """Check request's IP address and block the user if it is not valid.

        :return: an HttpResponse if there is an error to show, or None if everything was fine.
        """
        try:
            utils.clean_ip_address(self.request)
        except ValidationError:
            message = 'Unable to proceed with the payment'
            form.add_error('', message)
            response = self.form_invalid(form)
            response.status_code = 400
            response.reason_phrase = message
            return response
        return None


def check_recaptcha(request) -> Tuple[Optional[bool], str]:
    """Handles recaptcha verification and sets request.recaptcha_is_valid.

    Be sure to set settings.GOOGLE_RECAPTCHA_SECRET_KEY to a non-empty string,
    otherwise this function does nothing.

    :returns: None when no check was performed, or True/False indicating a
        successful resp. unsuccessful check.
    """

    my_log = log.getChild('check_recaptcha')
    recaptcha_response = request.POST.get('g-recaptcha-response') or ''
    if not recaptcha_response:
        my_log.warning('reCaptcha response not included in request')
        return (
            False,
            'ReCaptcha failed to check your request. Please disable script/ad '
            'blockers and try again.',
        )

    data = {'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY, 'response': recaptcha_response}
    try:
        r = recaptcha_session.post('https://www.google.com/recaptcha/api/siteverify', data=data)
    except IOError as ex:
        my_log.exception('Error communicating with Google reCAPTCHA service')

        full_url = request.build_absolute_uri()
        mail_admins(
            'reCaptcha communication error',
            f'A request on {full_url} needed a reCaptcha check. The HTTPS request'
            f' failed with exception {ex}',
        )

        return None, 'There was a communication error checking reCAPTCHA. Please try again.'

    if r.status_code != 200:
        my_log.error("Error code %d verifying reCaptcha: %s", r.status_code, r.text)

        full_url = request.build_absolute_uri()
        mail_admins(
            'reCaptcha communication error',
            f'A request on {full_url} needed a reCaptcha check. The HTTPS request'
            f' failed with error {r.status_code} and this message:\n{r.text}',
        )

        return None, 'There was a communication error checking reCAPTCHA. Please try again.'

    result = r.json()

    if not result.get('success', False):
        my_log.warning(
            "reCaptcha failed to verify for URL %s: %s", request.build_absolute_uri(), r.text
        )
        return False, 'ReCaptcha failed to verify that you are human being. Please try again.'

    # Check that nobody is trying to fake the response via some other website.
    hostname = result.get('hostname')
    if not validate_host(hostname, settings.ALLOWED_HOSTS):
        my_log.error(
            "reCaptcha verified but for an unexpected hostname %r for URL %s",
            hostname,
            request.build_absolute_uri(),
        )
        return (
            False,
            'reCaptcha verified, but for an unexpected hostname. Please try again. If '
            'this keeps happening, send an email to production@blender.org.',
        )

    my_log.debug('reCaptcha verfied')
    return True, ''


class CheckoutView(AbstractPaymentView):
    """Perform the checkout procedure for a subscription."""

    template_name = 'checkout/checkout.html'
    form_class = CheckoutForm

    log = log.getChild('CheckoutView')

    plan: models.Plan
    plan_variation: models.PlanVariation

    def dispatch(self, request, *args, **kwargs):
        # Get the prerequisites for handling any request in this view.
        self.plan = get_object_or_404(models.Plan, pk=kwargs['plan_id'])
        self.plan_variation = get_object_or_404(
            self.plan.variations.active(), pk=kwargs['plan_variation_id']
        )
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs) -> dict:
        ctx = {
            **super().get_context_data(**kwargs),
            'plan': self.plan,
            'plan_variation': self.plan_variation,
        }
        return ctx

    def get_form_kwargs(self) -> dict:
        return {
            **super().get_form_kwargs(),
            'instance': self.customer.billing_address,
        }

    def get_form(self, form_class=None):
        form = super().get_form(form_class)

        if self.request.method == 'GET':
            # Do NOT call this here on a POST. At this point in the code,
            # the form hasn't been updated with the POSTed data yet,
            # and thus will nag about recent subscriptions even when the user has confirmed.
            recent_subs = self._check_recently_created_subscription(form)
            if recent_subs is not None:
                self._update_form_for_recent_subscription(form, recent_subs)

        return form

    def get_initial(self) -> dict:
        return {
            **super().get_initial(),
            'price': self.plan_variation.price.decimals_string,

looper/views/mixins.py
from typing import Optional

from django.core.exceptions import ValidationError
from django.http import HttpResponse, HttpResponseBadRequest
import django.forms

import looper.utils as utils


class ExpectReadableIPAddressMixin:
    def _check_customer_ip_address(self, form: django.forms.Form = None) -> Optional[HttpResponse]:
        """Check request's IP address and block the user if it is not valid.

        :return: an HttpResponse if there is an error to show, or None if everything was fine.
        """
        try:
            utils.clean_ip_address(self.request)
        except ValidationError:
            message = 'Unable to proceed with the payment'
            if form:
                form.add_error('', message)
                response = self.form_invalid(form)
            else:
                response = HttpResponseBadRequest()
            response.status_code = 400
            response.reason_phrase = message
            return response
        return None

looper/templates/looper/settings/billing_address.html
{% extends "settings/base.html" %}
{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">Billing Address</h2>
<form class="p-3" id="billing-address-form" method="post">
  <ul class="form">
    {% csrf_token %}
    {{ form.as_ul }}
  </ul>
  <hr/>
  <button class="btn btn-success px-5 mt-3" id="submit-billing-info" type="submit"><i class="fa fa-check"></i>Save Changes</button>
</form>{% endblock content_settings %}

looper/templates/looper/settings/payment_method_change_braintree.html
{% extends "settings/base.html" %}
{% load pipeline %}

{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">
  Change Payment Method
  
</h2>
<p>Your <strong>{{ subscription.plan.name }} {{ subscription.plan.product.name }}</strong> is currently using
  <strong>{{ current_payment_method.recognisable_name }}</strong> as payment method.
  
  Feel free to change it below.
  
</p>
<div class="m-3">
  <form class="form" id="payment-method-change-form" method="post"
      data-looper-payment-form="true"
      data-braintree-client-token="{{ client_token }}">{% csrf_token %}
    <section class="checkout-form-fields pt-4">
      <ul class="form">{{ form.as_ul }}</ul>
      <div id="gateway-errors"></div>
    </section>
    <hr/>
    <div class="d-flex align-items-center pt-3"><a class="p-3" href="{% url 'settings_home' %}">Cancel</a>
      <button id="submit-button" class="ml-auto btn-success form-submit px-5"
              type="submit"
              aria-disabled="true" disabled
              ><i class="fa fa-check"></i>Switch Payment method</button>
    </div>
  </form>
</div>{% endblock content_settings %}
{% block footer_scripts%}{{ block.super }}
{% include "looper/scripts.html" %}
{% endblock footer_scripts%}

looper/templates/looper/settings/payment_method_delete.html
{% extends "settings/base.html" %}
{% block content_settings %}
<h2 class="mt-2 text-secondary">Payment Methods</h2>
<form method="post">{% csrf_token %}
  <p>Are you sure you want to delete payment method "{{ object }}"?</p>
  <p class="pt-3">
    <input class="btn btn-filled-danger px-5" type="submit" value="Confirm Deletion"/><a class="pl-3" href="{% url 'looper:payment_methods' %}">Cancel</a>
  </p>
</form>{% endblock content_settings %}

looper/templates/looper/settings/payment_method_not_used.html
{% extends "settings/base.html" %}
{% block content_settings %}
<h2 class="mt-2 text-secondary">Payment Method Not Used</h2>
<p>The payment method you selected, {{ paymeth.recognisable_name }}, is not used in any active recurring payment.</p><a class="btn btn-filled-success px-5" href="{% url 'looper:payment_methods' %}">Ok</a>{% endblock content_settings %}

looper/templates/looper/settings/payment_methods.html
{% extends "settings/base.html" %}
{% block head %}
<style>
  td.actions a {
  	padding: 1mm 2mm;
  }
</style>{% endblock %}
{% block content_settings %}
<h2 class="mt-2 text-secondary">Payment Methods</h2>
<p class="pb-3">
  Here you can view and delete payment methods. You can add a new one while changing an old
  one, or while paying for something.
  
</p>
<table class="table table-striped box m-3">
  <tbody>
    {% for payment_method in object_list %}
    {% with payment_method.gateway_properties as pm_props %}
    <tr>{% if pm_props is None %}
      <td>
        Invalid payment method; just delete this one. This can happen when
        the payment method was deleted at the payment service provider.
      </td>{% else %}
      <td><img class="img-responsive" src="{{ pm_props.image_url }}"/></td>{% if payment_method.method_type == 'cc' %}
      <td>{{ pm_props.card_type }}</td>
      <td>Ending with <strong>{{ pm_props.last_4 }}</strong></td>
      <td>Expires <strong>{{ pm_props.expiration_date }}</strong></td>{% else %}
      <td colspan="3">{{ pm_props.recognisable_name }}</td>{% endif %}
      {% endif %}
      <td class="actions"><a class="text-danger" href="{% url 'looper:payment_method_delete' pk=payment_method.pk %}">Remove</a></td>
    </tr>{% endwith %}
    {% endfor %}
  </tbody>
</table>{% endblock content_settings %}

looper/templates/looper/settings/personal_info.html
{% extends "settings/base.html" %}
{% block content_settings %}
<h2 class="mt-2 text-secondary">Personal Information</h2>
<form class="p-3" id="customer-form" method="post">
  <ul class="form">
    {% csrf_token %}
    {{ form.as_ul }}
  </ul>
  <hr/>
  <button class="btn btn-success px-5 mt-3" id="submit-customer" type="submit"><i class="fa fa-check"></i>Save Changes</button>
</form>{% endblock content_settings %}

looper/templates/looper/settings/receipt.html
{% extends "settings/base.html" %}
{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">Blender Development Fund {% if order.subscription.plan.product.type == 'DNT' or order.product.type == 'DNT' %}Donation {% endif %}Receipt</h2>
<hr/>
<div class="receipt mt-4">
  <dl class="dl-horizontal">
    <dt>Receipt ID</dt>
    <dd>{{ order.id }}</dd>
    <dt>Payment received on</dt>
    <dd>{{ order.paid_at|default:order.created_at }}</dd>
  </dl>
  {% if order.subscription.plan.name %}
  <h4>Membership</h4>
  <dl class="dl-horizontal">
    <dt>Membership level</dt>
    <dd>{{ order.subscription.plan.name }}</dd>
  </dl>
  {% endif %}
  <h4>Billing Address</h4>
  <dl class="dl-horizontal">
    <dt>Address</dt>
    <dd>{{ order.billing_address|linebreaksbr }}</dd>
    <dt>E-mail</dt>
    <dd>{{ order.email }}</dd>
    {% if order.vat_number %}
    <dt>VATIN</dt>
    <dd>{{ order.vat_number }}</dd>
    {% endif %}
  </dl>
  <h4>Payment Information</h4>
  <dl class="dl-horizontal">
    {% if order.subscription.plan.product.description %}
      <dd>{{ order.subscription.plan.product.description }}</dd>
    {% elif order.product.description %}
      <dd>{{ order.product.description }}</dd>
    {% endif %}
    <dt>Amount paid</dt>
    <dd>{{ order.price.with_currency_symbol_nonocents }}</dd>{% with refunded=order.refunded %}
    {% if refunded %}
    <dt>Amount refunded</dt>
    <dd>{{ refunded.with_currency_symbol_nonocents }}</dd>{% endif %}
    {% endwith %}
    {% if order.payment_method.recognisable_name %}
    <dt>Payment method</dt>
    <dd>{{ order.payment_method.recognisable_name }}</dd>
    {% endif %}
  </dl>
</div>{% endblock content_settings %}

looper/templates/looper/settings/receipt_pdf.html
{% extends "pdf_layout.html" %}

{% block title %}Blender Development Fund {% if order.subscription.plan.product.type == 'DNT' or order.product.type == 'DNT' %}Donation {% endif %}Receipt #{{ order.display_number }}{% endblock %}
{% block main_content %}
<table style="width: 40em">
  <tr>
    <td colspan="2">
      <h4>Blender Development Fund {% if order.subscription.plan.product.type == 'DNT' or order.product.type == 'DNT' %}Donation {% endif %}Receipt</h4>
    </td>
  </tr>
  <tr>
    <th>Receipt ID</th>
    <td>{{ order.display_number }}</td>
  </tr>
  <tr>
    <th>Payment received on</th>
    <td>{{ order.paid_at|default:order.created_at|date:"N j, Y" }}</td>
  </tr>
  {% if order.subscription.plan %}
  <tr>
    <th>Membership level</th>
    <td>{{ order.subscription.plan.name }}</td>
  </tr>
  {% endif %}
  {% if order.subscription.plan.product.description %}
    <tr>
      <th></th>
      <td>{{ order.subscription.plan.product.description }}</td>
    </tr>
  {% elif order.product %}
    <tr>
      <th>Description</th>
      <td>{{ order.product.description }}</td>
    </tr>
  {% endif %}
  <tr>
    <td colspan="2">
      <h4>Billing Address</h4>
    </td>
  </tr>
  <tr>
    <th>Address</th>
    <td>{{ order.billing_address|default:"-"|linebreaksbr }}</td>
  </tr>
  <tr>
    <th>E-mail</th>
    <td>{{ order.email }}</td>
  </tr>
  {% if order.vat_number %}
    <tr>
      <th>VATIN</th>
      <td>{{ order.vat_number }}</td>
    </tr>
  {% endif %}
  <tr>
    <td colspan="2">
      <h4>Payment Information</h4>
    </td>
  </tr>
  <tr>
    <th>Amount paid</th>
    <td>{{ order.price.with_currency_symbol_nonocents }}</td>{% with refunded=order.refunded %}
    {% if refunded %}
  </tr>
  <tr>
    <th>Amount refunded</th>
    <td>{{ refunded.with_currency_symbol_nonocents }}</td>{% endif %}
    {% endwith %}
  </tr>
  {% if order.payment_method.recognisable_name %}
  <tr>
    <th>Payment method</th>
    <td>{{ order.payment_method.recognisable_name }}</td>
  </tr>
  {% endif %}
  {% if order.payment_method.method_type == 'ba' %}
  <tr>
    <th>Bank details</th>
    <td>Bank: ING Bank, P/O Box 1800, Amsterdam, the Netherlands<br/>
      BIC/Swift code: INGB NL 2A (international code)<br/>
      IBAN: NL45 INGB 0009356121 (for euro accounts)<br/>
      Account #: 93 56 121
    </td>
  </tr>{% endif %}
</table>{% endblock %}

looper/templates/looper/settings/receipts.html
{% extends "settings/base.html" %}

{% block content_settings %}
{{ block.super }}
<h2 class="mt-2 text-secondary">Receipts</h2>{% if orders %}
<table class="table table-sm table-hover text-center table-receipts">
  <thead>
    <tr>
      <th>Receipt ID</th>
      <th></th>
      <th>Amount Paid</th>
      <th>Paid At</th>
      <th></th>
    </tr>
  </thead>
  <tbody>{% for o in orders %}
    <tr>
      <td>{{ o.id }}</td>
      <td>{{ o.name }}</td>
      <td>{{ o.price.with_currency_symbol_nonocents }}</td>
      <td>{{ o.paid_at|date:"Y-m-d" }}</td>
      <td><a href="{% url 'settings_receipt' order_id=o.pk %}">View</a><br/><a href="{% url 'settings_receipt_pdf' order_id=o.pk %}">Download&nbsp;PDF</a>{% if can_woosh %}<br/><a class="px-3" href="{% url 'admin:looper_order_change' object_id=o.pk %}">🚀</a>{% endif %}</td>
    </tr>{% endfor %}
  </tbody>
</table>{% else %}
<p>You have no receipts.</p>{% endif %}
{% endblock content_settings %}